# Generated by Django 4.0 on 2022-06-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miawwards', '0004_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
